version: '3'

services:
  php:
    build:
      context: docker
      dockerfile: dev/php/Dockerfile
    working_dir: /var/www/packtpub-bot
    volumes:
      - .:/var/www/packtpub-bot
    env_file:
      - .env