version: '3.7'

services:
  ppbot:
    build:
      context: .
      dockerfile: docker/prod/php/Dockerfile
    image: ppbot
    working_dir: /var/www/packtpub-bot
    env_file:
      - .env
    entrypoint: php bin/console
